# Generated by Django 4.2.7 on 2025-11-12 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='unavailabledate',
            unique_together={('accommodation', 'date')},
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['city', 'status'], name='accommodati_city_09c965_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['price_per_night'], name='accommodati_price_p_f92f02_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['created_at'], name='accommodati_created_2cd983_idx'),
        ),
    ]
