# Generated by Django 5.2.8 on 2025-12-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_alter_accommodation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='advance_booking_days',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
